<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { UiPage, UiAlert, UiCard, UiSelect, UiButton } from '@go-tangra/ui'
import { get, explain } from '@/api/client'
import type { MetricSeries } from '@/api/types'
import { usePeriod } from '@/components/period'
import PeriodFilter from '@/components/PeriodFilter.vue'
import { useLatest } from '@/components/latest'
import { formatTime } from '@/components/timezone'
const {from,to,query}=usePeriod();const extension=ref(''),metric=ref('asterisk_active_calls'),error=ref(''),range=ref<MetricSeries[]>([]),instant=ref<MetricSeries[]>([]),directory=ref<{title:string;value:string}[]>([])
const metrics=[{title:'Active calls',value:'asterisk_active_calls'},{title:'AMI freshness',value:'asterisk_ami_fresh'},{title:'PBX uptime',value:'asterisk_uptime_seconds'},{title:'Active channels',value:'asterisk_channels_active'},{title:'SIP peer availability',value:'asterisk_sip_peer_up'},{title:'PJSIP endpoint availability',value:'asterisk_pjsip_endpoint_up'},{title:'Queue callers',value:'asterisk_queue_callers'},{title:'Queue completions',value:'asterisk_queue_completed_calls'},{title:'Queue abandonments',value:'asterisk_queue_abandoned_calls'},{title:'Registered contacts',value:'asterisk_contact_registered'},{title:'Contact round-trip time',value:'asterisk_contact_rtt_milliseconds'},{title:'Receive media quality',value:'asterisk_rtp_receive_mos'}]
const latest=useLatest()
async function load(){const signal=latest.start();error.value='';try{const q=metric.value+(extension.value?'{extension='+JSON.stringify(extension.value)+'}':'');const period=query();const [series,now]=await Promise.all([get<{items:MetricSeries[]}>('/api/asterisk/dashboard/query_range',{query:q,start:period.from,end:period.to,stepSeconds:Math.max(60,Math.ceil((Date.parse(period.to)-Date.parse(period.from))/1000/500))},{},signal),get<{items:MetricSeries[]}>('/api/asterisk/dashboard/query',{query:q},{},signal)]);if(signal.aborted)return;range.value=series.items;instant.value=now.items}catch(e){if(!signal.aborted)error.value=explain(e)}}
onMounted(async()=>{try{directory.value=(await get<{items:{extension:string;name:string}[]}>('/api/asterisk/directory/extensions')).items.map(e=>({title:e.extension+' '+e.name,value:e.extension}))}catch(e){error.value=explain(e)};await load()})
const seriesKey=(s:MetricSeries)=>JSON.stringify(Object.entries(s.labels).sort(([a],[b])=>a.localeCompare(b)))
const current=(s:MetricSeries)=>instant.value.find(i=>seriesKey(i)===seriesKey(s))?.samples[0]
const points=(s:MetricSeries)=>{const vals=s.samples.filter(p=>p.hasValue&&p.value!==null);const max=Math.max(1,...vals.map(p=>p.value??0));return s.samples.map((p,i)=>p.hasValue?`${i*100/Math.max(1,s.samples.length-1)},${40-(p.value??0)*38/max}`:'').join(' ')}
</script>
<template><UiPage title="PBX monitoring"><template #filters><PeriodFilter v-model:from="from" v-model:to="to" @submit="load"/><UiSelect id="metric" v-model="metric" label="Metric" :clearable="false" :options="metrics"/><UiSelect id="monitor-extension" v-model="extension" label="Extension" :options="directory"/><UiButton @click="load">Refresh</UiButton></template><UiAlert v-if="error" kind="warning">{{error}}</UiAlert><p v-if="!range.length && !error">No samples in this period.</p><UiCard v-for="s in range" :key="seriesKey(s)"><h3>{{Object.entries(s.labels).map(([k,v])=>k+'='+v).join(' · ')||metric}}</h3><p>Current: {{current(s)?.hasValue?current(s)?.value:'Unavailable'}}</p><svg v-if="s.samples.every(p=>p.hasValue)" viewBox="0 0 100 42" role="img" aria-label="Metric series" class="w-full h-40"><polyline :points="points(s)" fill="none" stroke="currentColor" stroke-width="0.5"/></svg><p v-else>Some samples are missing; gaps are listed below.</p><details><summary>Samples</summary><ol><li v-for="p in s.samples" :key="p.time">{{formatTime(p.time)}} · {{p.hasValue?p.value:'Missing'}}</li></ol></details></UiCard></UiPage></template>
