import { flushPromises, mount } from '@vue/test-utils'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { backoff } from '../../src/components/backoff'
import LiveView from '../../src/views/live/index.vue'
class FakeSource extends EventTarget {static all:FakeSource[]=[];closed=false;onerror:(()=>void)|null=null;constructor(public url:string){super();FakeSource.all.push(this)}close(){this.closed=true}fail(){this.onerror?.()}open(){this.dispatchEvent(new Event('open'))}}
const json=(body:unknown)=>({ok:true,status:200,json:async()=>body})
let hidden=false
beforeEach(()=>{vi.useFakeTimers();FakeSource.all=[];hidden=false;vi.spyOn(Math,'random').mockReturnValue(1);Object.defineProperty(document,'hidden',{configurable:true,get:()=>hidden});vi.stubGlobal('EventSource',FakeSource);vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/capabilities')?json({live:{available:true,fresh:true}}):json({calls:[],generation:1,fresh:true,updated:''})))})
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks()})
it('jitters an exponential delay capped at 30 seconds',()=>{expect(backoff(0,()=>0)).toBe(500);expect(backoff(0,()=>1)).toBe(1000);expect(backoff(3,()=>1)).toBe(8000);expect(backoff(20,()=>1)).toBe(30000);expect(backoff(20,()=>0)).toBe(15000)})
it('backs off between failed streams and resets once a stream opens',async()=>{const view=mount(LiveView);await flushPromises();expect(FakeSource.all).toHaveLength(1);FakeSource.all[0]!.fail();expect(FakeSource.all[0]!.closed).toBe(true);await vi.advanceTimersByTimeAsync(999);expect(FakeSource.all).toHaveLength(1);await vi.advanceTimersByTimeAsync(1);await flushPromises();expect(FakeSource.all).toHaveLength(2);FakeSource.all[1]!.fail();await vi.advanceTimersByTimeAsync(1999);expect(FakeSource.all).toHaveLength(2);await vi.advanceTimersByTimeAsync(1);await flushPromises();expect(FakeSource.all).toHaveLength(3);FakeSource.all[2]!.open();FakeSource.all[2]!.fail();await vi.advanceTimersByTimeAsync(1000);await flushPromises();expect(FakeSource.all).toHaveLength(4);view.unmount();expect(FakeSource.all[3]!.closed).toBe(true);await vi.advanceTimersByTimeAsync(60000);expect(FakeSource.all).toHaveLength(4)})
it('closes the stream in a hidden tab and reopens it when visible',async()=>{const view=mount(LiveView);await flushPromises();hidden=true;document.dispatchEvent(new Event('visibilitychange'));expect(FakeSource.all[0]!.closed).toBe(true);await vi.advanceTimersByTimeAsync(60000);expect(FakeSource.all).toHaveLength(1);hidden=false;document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(FakeSource.all).toHaveLength(2);expect(FakeSource.all[1]!.closed).toBe(false);view.unmount();expect(FakeSource.all[1]!.closed).toBe(true)})
