// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-asterisk/internal/cert"
	"github.com/go-tangra/go-tangra-asterisk/internal/data"
	"github.com/go-tangra/go-tangra-asterisk/internal/data/providers"
	"github.com/go-tangra/go-tangra-asterisk/internal/server"
	"github.com/go-tangra/go-tangra-asterisk/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	config, err := data.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	mySQLClients, cleanup, err := data.NewMySQLClients(context, config)
	if err != nil {
		return nil, nil, err
	}
	cdrRepo := data.NewCdrRepo(context, mySQLClients)
	cdrService := service.NewCdrService(context, cdrRepo)
	statsRepo := data.NewStatsRepo(context, mySQLClients)
	statsService := service.NewStatsService(context, statsRepo)
	pjsipRegRepo := data.NewPJSIPRegRepo(context, mySQLClients)
	registrationService := service.NewRegistrationService(context, pjsipRegRepo)
	prometheusClient := data.NewPrometheusClient(config)
	dashboardService := service.NewDashboardService(context, prometheusClient)
	callRegistry := providers.NewCallRegistry()
	liveCallsService := service.NewLiveCallsService(context, callRegistry)
	grpcServer := server.NewGRPCServer(context, certManager, cdrService, statsService, registrationService, dashboardService, liveCallsService)
	httpServer := server.NewHTTPServer(context, mySQLClients, callRegistry)
	client, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	listener := providers.NewAMIListener(context, config, pjsipRegRepo, callRegistry)
	app := newApp(context, grpcServer, httpServer, client, listener)
	return app, func() {
		cleanup()
	}, nil
}
